version: '3.8'
services:
   mysql-meta:
     platform: linux/amd64
     image: mysql:8.0.29
     ports:
     - "3307:3306"
     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
     environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=foo
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=test
     volumes:
     - mysql-meta:/var/lib/mysql
   mysql-sharding1:
     platform: linux/amd64
     image: mysql:8.0.29
     ports:
     - "3308:3306"
     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
     environment:
     - MYSQL_USER=foo
     - MYSQL_PASSWORD=1234
     - MYSQL_ROOT_PASSWORD=1234
     - MYSQL_DATABASE=test
     volumes:
     - mysql-sharding1:/var/lib/mysql
   mysql-sharding2:
     platform: linux/amd64
     image: mysql:8.0.29
     ports:
     - "3309:3306"
     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
     environment:
     - MYSQL_USER=foo
     - MYSQL_PASSWORD=1234
     - MYSQL_ROOT_PASSWORD=1234
     - MYSQL_DATABASE=test
     volumes:
     - mysql-sharding2:/var/lib/mysql
   mysql-sharding3:
     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
     platform: linux/amd64
     image: mysql:8.0.29
     ports:
     - "3310:3306"
     environment:
     - MYSQL_USER=foo
     - MYSQL_DATABASE=test
     - MYSQL_PASSWORD=1234
     - MYSQL_ROOT_PASSWORD=1234
     volumes:
     - mysql-sharding3:/var/lib/mysql
   mysql-sharding4:
     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
     platform: linux/amd64
     image: mysql:8.0.29
     ports:
     - "3311:3306"
     environment:
     - MYSQL_USER=foo
     - MYSQL_PASSWORD=1234
     - MYSQL_DATABASE=test
     - MYSQL_ROOT_PASSWORD=1234
     volumes:
     - mysql-sharding4:/var/lib/mysql
   redis:
     image: redis
     ports:
     - "6379:6379"

volumes:
  mysql-meta:
  mysql-sharding1:
  mysql-sharding2:
  mysql-sharding3:
  mysql-sharding4:
