version: '3.8'
services:
   mysql:
     platform: linux/amd64
     image: mysql:8.0.29
     ports:
     - "9306:3306"
     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
     environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=foo
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=covidboard
     volumes:
     - mysql:/var/lib/mysql

volumes:
  mysql:
